name:                openapi-typed
version:             0.0.0.0
github:              "meeshkan/openapi-haskell"
license:             BSD3
author:              "Mike Solomon"
maintainer:          "mike@meeshkan.com"
copyright:           "2020 Meeshkan Oy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/meeshkan/openapi-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  openapi-typed-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openapi-typed
